# Generated by Django 3.1.5 on 2021-01-25 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='assembly_line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='pauid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pa_date', models.DateTimeField(verbose_name='production actual date')),
                ('shift', models.IntegerField(default=0)),
                ('assembly_line_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.assembly_line')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hourly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour1', models.IntegerField(default=0)),
                ('hour2', models.IntegerField(default=0)),
                ('hour3', models.IntegerField(default=0)),
                ('hour4', models.IntegerField(default=0)),
                ('hour5', models.IntegerField(default=0)),
                ('hour6', models.IntegerField(default=0)),
                ('hour7', models.IntegerField(default=0)),
                ('hour8', models.IntegerField(default=0)),
                ('hour9', models.IntegerField(default=0)),
                ('hour10', models.IntegerField(default=0)),
                ('hour11', models.IntegerField(default=0)),
                ('hour12', models.IntegerField(default=0)),
                ('pauid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pauid')),
            ],
        ),
        migrations.AddField(
            model_name='assembly_line',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department'),
        ),
    ]
