# Use root/example as user/password credentials
version: '3.1'

services:

  apache2:
    image: php:7.3-apache
    build: 
      context: ./apache2
    ports: 
       - 80:80
    depends_on: 
        - mysql
    links: 
        - mysql

  mysql:
    image: mysql
    build:
      context: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example1
      MYSQL_DATABASE: webpts
      volumes:
        mysql/save:/var/lib/mysql
        mysql/init:/tmp/database
      ports:
        3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
