# Generated by Django 3.1.6 on 2021-02-08 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productionactual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hourly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour1', models.IntegerField(default=0)),
                ('hour2', models.IntegerField(default=0)),
                ('hour3', models.IntegerField(default=0)),
                ('hour4', models.IntegerField(default=0)),
                ('hour5', models.IntegerField(default=0)),
                ('hour6', models.IntegerField(default=0)),
                ('hour7', models.IntegerField(default=0)),
                ('hour8', models.IntegerField(default=0)),
                ('hour9', models.IntegerField(default=0)),
                ('hour10', models.IntegerField(default=0)),
                ('hour11', models.IntegerField(default=0)),
                ('productionactual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.productionactual')),
            ],
        ),
    ]
