# Generated by Django 3.1.6 on 2021-02-15 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productionactual', '0003_auto_20210215_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_number', models.IntegerField(max_length=1)),
                ('shift_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='productionactual',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.shift'),
        ),
    ]
