# Generated by Django 3.1.7 on 2021-03-29 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_name', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FourM', models.CharField(max_length=7)),
                ('defect_code', models.CharField(max_length=10)),
                ('defect_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fourM', models.CharField(max_length=7)),
                ('downtime_code', models.CharField(max_length=5)),
                ('planned', models.BooleanField(default=False)),
                ('default_recovery_time', models.FloatField(default=0.0, help_text='how long of downtime', max_length=7)),
                ('downtime_description', models.CharField(max_length=50)),
                ('assembly_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.assemblyline')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PartNumber', models.CharField(max_length=15)),
                ('TeamMember', models.CharField(max_length=2)),
                ('CycleTime', models.FloatField(max_length=4)),
                ('ToteQuantity', models.IntegerField(default=0)),
                ('assembly_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.assemblyline')),
            ],
            options={
                'ordering': ['assembly_line', 'PartNumber', 'TeamMember', 'CycleTime'],
            },
        ),
        migrations.CreateModel(
            name='ProductionActual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular ProductionActual', primary_key=True, serialize=False)),
                ('pa_date', models.DateField(verbose_name='production actual date')),
                ('assembly_line_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.assemblyline')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_number', models.IntegerField()),
                ('shift_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Hourly',
            fields=[
                ('ProductionActual', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='productionactual.productionactual')),
                ('hour1', models.IntegerField(default=0)),
                ('hour2', models.IntegerField(default=0)),
                ('hour3', models.IntegerField(default=0)),
                ('hour4', models.IntegerField(default=0)),
                ('hour5', models.IntegerField(default=0)),
                ('hour6', models.IntegerField(default=0)),
                ('hour7', models.IntegerField(default=0)),
                ('hour8', models.IntegerField(default=0)),
                ('hour9', models.IntegerField(default=0)),
                ('hour10', models.IntegerField(default=0)),
                ('hour11', models.IntegerField(default=0)),
                ('hour12', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, help_text='Run Number')),
                ('partal_start', models.IntegerField(default=0, help_text='Start Partal quanity')),
                ('partal_end', models.IntegerField(default=0, help_text='End Partal quanity')),
                ('finished_goods', models.IntegerField(default=0, help_text='How many totes completed')),
                ('kanban_count', models.IntegerField(default=0, help_text='How many Kanbans in post for current shift')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('finish_time', models.TimeField(blank=True, null=True)),
                ('plan_down_time', models.IntegerField(default=0)),
                ('net_ope_time', models.IntegerField(default=0)),
                ('plan_quanity', models.IntegerField(default=0)),
                ('result_quanity', models.IntegerField(default=0)),
                ('scrap_quanity', models.IntegerField(default=0)),
                ('repair_quanity', models.IntegerField(default=0)),
                ('analysis_quanity', models.IntegerField(default=0)),
                ('quarantine_quanity', models.IntegerField(default=0)),
                ('cabbage_patch_quanity', models.IntegerField(default=0)),
                ('unplan_downtime', models.IntegerField(default=0)),
                ('standard_time', models.IntegerField(default=0)),
                ('oa', models.IntegerField(default=0)),
                ('oa_without_downtime', models.IntegerField(default=0)),
                ('ProductionActual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.productionactual')),
                ('product_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.product')),
            ],
        ),
        migrations.AddField(
            model_name='productionactual',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.shift'),
        ),
        migrations.AddField(
            model_name='productionactual',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=40)),
                ('machine_name_short', models.CharField(max_length=5)),
                ('machine_name_actual', models.CharField(max_length=7)),
                ('assembly_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.assemblyline')),
            ],
        ),
        migrations.CreateModel(
            name='DowntimeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('down_time', models.TimeField(blank=True, null=True)),
                ('up_time', models.TimeField(blank=True, null=True)),
                ('recovery_time', models.FloatField(help_text='how long of downtime', max_length=7)),
                ('occurrence_multiplier', models.IntegerField(default=1, help_text='how many times did this happen')),
                ('noti_hancho', models.BooleanField(default=True)),
                ('noti_shokucho', models.BooleanField(default=False)),
                ('noti_maint', models.BooleanField(default=False)),
                ('noti_kocho', models.BooleanField(default=False)),
                ('ProductionActual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.productionactual')),
                ('downtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.downtime')),
                ('production_run', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productionactual.run')),
            ],
        ),
        migrations.AddField(
            model_name='downtime',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.machine'),
        ),
        migrations.CreateModel(
            name='DefectInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_quanity', models.IntegerField(default=1)),
                ('ProductionActual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.productionactual')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.defect')),
                ('production_run', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productionactual.run')),
            ],
        ),
        migrations.AddField(
            model_name='defect',
            name='Machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.machine'),
        ),
        migrations.AddField(
            model_name='defect',
            name='assembly_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.assemblyline'),
        ),
        migrations.AddField(
            model_name='assemblyline',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.department'),
        ),
    ]
