# Generated by Django 3.1.7 on 2021-03-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionactual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtime',
            name='downtime_description',
            field=models.CharField(max_length=300),
        ),
    ]
