# Generated by Django 3.1.6 on 2021-02-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionactual', '0004_auto_20210215_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionactual',
            name='pa_date',
            field=models.DateField(verbose_name='production actual date'),
        ),
    ]
