# Generated by Django 3.1.6 on 2021-03-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionactual', '0021_auto_20210324_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtimeinstance',
            name='noti_hancho',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='downtimeinstance',
            name='noti_kocho',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downtimeinstance',
            name='noti_maint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downtimeinstance',
            name='noti_shokucho',
            field=models.BooleanField(default=False),
        ),
    ]
