# Generated by Django 3.1.6 on 2021-02-15 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productionactual', '0005_auto_20210215_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='default_recovery_time',
            field=models.FloatField(default=0.0, help_text='how long of downtime', max_length=7),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_number',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='DowntimeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_time', models.FloatField(help_text='how long of downtime', max_length=7)),
                ('occurrence_multiplier', models.IntegerField(default=1, help_text='how many times did this happen')),
                ('ProductionActual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.productionactual')),
                ('downtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.downtime')),
            ],
        ),
        migrations.CreateModel(
            name='DefectInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_quanity', models.IntegerField(default=1)),
                ('ProductionActual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.productionactual')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.defect')),
            ],
        ),
    ]
