# Generated by Django 3.1.6 on 2021-02-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productionactual', '0006_auto_20210215_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourly',
            name='id',
        ),
        migrations.AlterField(
            model_name='hourly',
            name='ProductionActual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='productionactual.productionactual'),
        ),
    ]
