# Generated by Django 3.1.6 on 2021-02-23 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productionactual', '0007_auto_20210217_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourly',
            name='ProductionActual',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='productionactual.productionactual'),
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_num', models.IntegerField(default=0)),
                ('partal_start', models.IntegerField(default=0)),
                ('partal_end', models.IntegerField(default=0)),
                ('finished_goods', models.IntegerField(default=0)),
                ('kanban_count', models.IntegerField(default=0)),
                ('start_time', models.IntegerField(default=0)),
                ('finish_time', models.IntegerField(default=0)),
                ('plan_down_time', models.IntegerField(default=0)),
                ('net_ope_time', models.IntegerField(default=0)),
                ('plan_quanity', models.IntegerField(default=0)),
                ('result_quanity', models.IntegerField(default=0)),
                ('scrap_quanity', models.IntegerField(default=0)),
                ('repair_quanity', models.IntegerField(default=0)),
                ('analysis_quanity', models.IntegerField(default=0)),
                ('quarantine_quanity', models.IntegerField(default=0)),
                ('cabbage_patch_quanity', models.IntegerField(default=0)),
                ('unplan_downtime', models.IntegerField(default=0)),
                ('standard_time', models.IntegerField(default=0)),
                ('oa', models.IntegerField(default=0)),
                ('oa_without_downtime', models.IntegerField(default=0)),
                ('ProductionActual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.productionactual')),
                ('product_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productionactual.product')),
            ],
        ),
        migrations.AddField(
            model_name='defectinstance',
            name='production_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productionactual.run'),
        ),
        migrations.AddField(
            model_name='downtimeinstance',
            name='production_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productionactual.run'),
        ),
    ]
