# Generated by Django 3.1.6 on 2021-03-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionactual', '0008_auto_20210223_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='finish_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='run',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
