# Generated by Django 3.1.6 on 2021-03-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionactual', '0009_auto_20210301_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='finished_goods',
            field=models.IntegerField(default=0, help_text='How many totes completed'),
        ),
        migrations.AlterField(
            model_name='run',
            name='kanban_count',
            field=models.IntegerField(default=0, help_text='How many Kanbans in post for current shift'),
        ),
        migrations.AlterField(
            model_name='run',
            name='partal_end',
            field=models.IntegerField(default=0, help_text='End Partal quanity'),
        ),
        migrations.AlterField(
            model_name='run',
            name='partal_start',
            field=models.IntegerField(default=0, help_text='Start Partal quanity'),
        ),
        migrations.AlterField(
            model_name='run',
            name='run_num',
            field=models.IntegerField(default=0, help_text='Run Number'),
        ),
        migrations.AddConstraint(
            model_name='run',
            constraint=models.UniqueConstraint(fields=('ProductionActual', 'run_num'), name='unique run_num'),
        ),
    ]
