# Generated by Django 3.1.6 on 2021-03-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productionactual', '0010_auto_20210301_0527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='run_num',
            new_name='RunNumber',
        ),
    ]
