# Generated by Django 3.1.6 on 2021-03-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productionactual', '0020_auto_20210324_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downtimeinstance',
            old_name='finish_time',
            new_name='down_time',
        ),
        migrations.RenameField(
            model_name='downtimeinstance',
            old_name='start_time',
            new_name='up_time',
        ),
    ]
