# Generated by Django 3.1.7 on 2021-03-29 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productionactual', '0022_auto_20210327_0348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downtime',
            old_name='FourM',
            new_name='fourM',
        ),
        migrations.RenameField(
            model_name='downtime',
            old_name='Machine',
            new_name='machine',
        ),
    ]
