# Generated by Django 3.1.7 on 2021-03-29 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productionactual', '0023_auto_20210329_0803'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='run',
            name='unique number',
        ),
    ]
